"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const Unit_api_1 = __importDefault(require("../src/api/Unit.api"));
const Applicant_api_1 = __importDefault(require("../src/api/Applicant.api"));
const Purchaser_api_1 = __importDefault(require("../src/api/Purchaser.api"));
const Company_api_1 = __importDefault(require("../src/api/Company.api"));
const Product_api_1 = __importDefault(require("../src/api/Product.api"));
const Currency_api_1 = __importDefault(require("../src/api/Currency.api"));
const Project_api_1 = __importDefault(require("../src/api/Project.api"));
const Contract_api_1 = __importDefault(require("../src/api/Contract.api"));
const Payment_api_1 = __importDefault(require("../src/api/Payment.api"));
const Inventory_api_1 = __importDefault(require("../src/api/Inventory.api"));
const File_api_1 = __importDefault(require("../src/api/File.api"));
const FileLink_api_1 = __importDefault(require("../src/api/FileLink.api"));
const app = (0, express_1.default)();
app.use(express_1.default.json());
app.use((0, cors_1.default)());
app.use('/unit', Unit_api_1.default);
app.use('/applicant', Applicant_api_1.default);
app.use("/purchaser", Purchaser_api_1.default);
app.use("/company", Company_api_1.default);
app.use("/product", Product_api_1.default);
app.use('/currency', Currency_api_1.default);
app.use('/project', Project_api_1.default);
app.use('/contract', Contract_api_1.default);
app.use('/payment', Payment_api_1.default);
app.use('/inventory', Inventory_api_1.default);
app.use('/file', File_api_1.default);
app.use('/doc/link', FileLink_api_1.default);
exports.default = app;
